### ISSUE TITLE
Suggested plotting features

### ISSUE THREAD

**Issue by tombeesley** [victor-navarro/heidi#1]
Hi Victor - just been playing around with some MAC1975 simulations. It's a little difficult to read the graphs at the moment as the different lines are coloured with a continuous colour scale. Is there any chance you could implement an option to make the scale discrete, or even manual?

An additional nice plotting feature would be to specify which subplots (e.g., associations) you want to view. I guess I can dig in to the results and plot my own from there, but would be great to have an easy option to specify. Maybe I've missed something on that, but I couldn't see any documentation on it. 

Great work. thanks!

**Comment by victor-navarro** [comment]
Thanks for the suggestion, @tombeesley!

I'll add a scale selector on the `calmr.app` GUI with the default `ggplot2` colours. I'll add a selector function to the package, too (akin to `ggplot2::theme_set()`).

Regardless, as all the plots in the package are currently built via `ggplot2`, you could implement a temporary fix by passing new scales to each ggplot object returned by the plotting function.

Something along the lines of:

```
library(calmr)
library(ggplot2)
df <- get_design("blocking")[1, ]
exp <- run_experiment(df, model = "MAC1975")
ps <- plot(exp)

ps[[1]] + scale_colour_hue()
```

When filtering the data that goes into a plot, things get a little tricky. The app used to have a phase/trial/stimulus selection, but I got rid of it because it was difficult to maintain. I'll look into adding it back again with a toggle system instead of dropdown menus.

If you're looking into plotting subsets of data within the package, you'd have to subset the data and re-feed it to the ggplot2 object. via the `%+%` operator. You'd do something along the lines of:

```
library(calmr)
library(ggplot2)
df <- get_design("blocking")[1, ]
exp <- run_experiment(df, model = "MAC1975")
ps <- plot(exp)

ps[[1]] %+% subset(
  results(exp)$associabilities,
  phase == "P2" & s1 %in% c("L", "US")
)

```

The latest version of the package in the main branch has exposed a bunch of generic functions to plot different model bits, depending on the structure of the data. You might want to check `??plotting_functions`, but under the hood, they are all just ggplot calls on the model outputs (which you can get via `results` as shown above).

Hope that helps. Let me know if you had something else in mind, of course.

**Comment by tombeesley** [comment]
Hi Victor. Thanks for the quick response! Yes, adding a colour scale selector would be excellent. I managed to figure out how to get at the data in the package after I posted the query. One thing you might want to do (when time allows) is provide an example in your (excellent) help pages that would guide users through the data and how to plot subsets. 

Here's my own (tidyverse) method in case it's useful for anyone in the future (where STK is the output of the simulation):

```
vs_res <-
  results(STK)[["vs"]] %>%
  filter(s1 %in% c("A", "B", "V", "W"),
         s2 %in% c("O1", "O2")) %>%
  group_by(trial, s1, s2) %>%
  summarise(value = mean(value))

vs_res %>%
  ggplot(aes(x = trial, y = value, colour = s1)) +
  geom_line() +
  facet_grid(rows = vars(s2)) +
  labs(title = "Associative Strengths",
       colour = "Cue")
```

**Comment by victor-navarro** [comment]
Glad it was of help! Thanks, Tom. [Btw, some model outputs have changed in naming in the last version to make them more intelligible (e.g., `vs` has become `associations`, `as` has become the perhaps controversial `associabilities`)].

I'll pen up an "intermediate" vignette showing the experiment class's guts and how to use them. Some of the advanced vignettes include data manipulation, but I am afraid those code snippets are currently getting buried under the wall of text.

I've been giving the app a new coat of paint (including `plotly` plots), and I'm pretty happy with the results thus far. I think you'll like it too.

**Comment by victor-navarro** [comment]
Added functionality in version `0.6.3`.

**Comment by victor-navarro** [comment]
Added colour palette functionality in version `0.6.3`.

**Comment by victor-navarro** [comment]
Added `filter()` method to filter experiments in version `0.6.3`.

**Comment by tombeesley** [comment]
These new features are fantastic. The GUI is looking great now.
